### ISSUE TITLE
Add an open source license

### ISSUE THREAD

**Issue by richford** [rtavenar/SparseGroupLasso#1]
Hi @rtavenar,

Thanks for posting your python implementation on GitHub. I'm interested in using and extending your implementation of SGL for a research project, using sparse group lasso for regression of data generated from diffusion-weighted MRI. I've forked your repo on GitHub but noticed that you haven't included a license file. Would you consider adding an open source license to this project so that I could create derivative work from your code?

Thanks.

**Comment by rtavenar** [comment]
Hi @richford ,

I've added a license to make things clearer (BSD-2-clause).
By the way, I have [another implementation of SparseGroupLasso in Python with keras](https://github.com/rtavenar/keras_ssg_lasso) (so basically the optimization scheme will be different and coefficients for useless variables in your regression will never be exactly zero but very small, but it will run much faster) that you might be interested in.

**Comment by richford** [comment]
Great, thanks for the quick response! I'll also check out your keras implementation.
